/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedWardrobeRouteImport } from './routes/_authenticated/wardrobe'
import { Route as ApiImportConfigRouteImport } from './routes/api/import/config'
import { Route as ApiImportWardrobeRouteImport } from './routes/api/import/wardrobe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWardrobeRoute = AuthenticatedWardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiImportConfigRoute = ApiImportConfigRouteImport.update({
  id: '/api/import/config',
  path: '/api/import/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportWardrobeRoute = ApiImportWardrobeRouteImport.update({
  id: '/api/import/wardrobe',
  path: '/api/import/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wardrobe': typeof AuthenticatedWardrobeRoute
  '/api/import/config': typeof ApiImportConfigRoute
  '/api/import/wardrobe': typeof ApiImportWardrobeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/wardrobe': typeof AuthenticatedWardrobeRoute
  '/api/import/config': typeof ApiImportConfigRoute
  '/api/import/wardrobe': typeof ApiImportWardrobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/wardrobe': typeof AuthenticatedWardrobeRoute
  '/api/import/config': typeof ApiImportConfigRoute
  '/api/import/wardrobe': typeof ApiImportWardrobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/wardrobe'
    | '/api/import/config'
    | '/api/import/wardrobe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/wardrobe'
    | '/api/import/config'
    | '/api/import/wardrobe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/_authenticated/wardrobe'
    | '/api/import/config'
    | '/api/import/wardrobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiImportConfigRoute: typeof ApiImportConfigRoute
  ApiImportWardrobeRoute: typeof ApiImportWardrobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wardrobe': {
      id: '/_authenticated/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof AuthenticatedWardrobeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/import/config': {
      id: '/api/import/config'
      path: '/api/import/config'
      fullPath: '/api/import/config'
      preLoaderRoute: typeof ApiImportConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/wardrobe': {
      id: '/api/import/wardrobe'
      path: '/api/import/wardrobe'
      fullPath: '/api/import/wardrobe'
      preLoaderRoute: typeof ApiImportWardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWardrobeRoute: typeof AuthenticatedWardrobeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWardrobeRoute: AuthenticatedWardrobeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiImportConfigRoute: ApiImportConfigRoute,
  ApiImportWardrobeRoute: ApiImportWardrobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
