-- Data API grants (RLS policies already restrict rows; these grants make tables reachable)
GRANT SELECT, INSERT, UPDATE, DELETE ON public.wardrobes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.garments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.garment_images TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.outfits TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.outfit_garments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.wishlist_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.model_profiles TO authenticated;
GRANT SELECT, UPDATE ON public.profiles TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT SELECT ON public.credit_balances TO authenticated;
GRANT SELECT ON public.credit_ledger TO authenticated;
GRANT SELECT ON public.ai_jobs TO authenticated;
GRANT SELECT ON public.ai_usage TO authenticated;
GRANT SELECT ON public.ai_wallets TO authenticated;
GRANT SELECT ON public.ai_topups TO authenticated;
GRANT SELECT ON public.subscriptions TO authenticated;
GRANT SELECT ON public.invites TO authenticated;
GRANT INSERT, SELECT ON public.analytics_events TO authenticated;

GRANT ALL ON public.wardrobes TO service_role;
GRANT ALL ON public.garments TO service_role;
GRANT ALL ON public.garment_images TO service_role;
GRANT ALL ON public.outfits TO service_role;
GRANT ALL ON public.outfit_garments TO service_role;
GRANT ALL ON public.wishlist_items TO service_role;
GRANT ALL ON public.model_profiles TO service_role;
GRANT ALL ON public.profiles TO service_role;
GRANT ALL ON public.user_roles TO service_role;
GRANT ALL ON public.credit_balances TO service_role;
GRANT ALL ON public.credit_ledger TO service_role;
GRANT ALL ON public.ai_jobs TO service_role;
GRANT ALL ON public.ai_usage TO service_role;
GRANT ALL ON public.ai_wallets TO service_role;
GRANT ALL ON public.ai_topups TO service_role;
GRANT ALL ON public.ai_credentials TO service_role;
GRANT ALL ON public.subscriptions TO service_role;
GRANT ALL ON public.invites TO service_role;
GRANT ALL ON public.analytics_events TO service_role;
GRANT ALL ON public.app_config TO service_role;
GRANT ALL ON public.billing_events TO service_role;
GRANT ALL ON public.trial_runs TO service_role;